"""create site measurements table

Revision ID: f91505449b2f
Revises: bfe4dd87fadc
Create Date: 2026-09-17 19:15:03.032857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f91505449b2f'
down_revision: Union[str, Sequence[str], None] = 'bfe4dd87fadc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_measurements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('measurement_date', sa.Date(), nullable=False),
    sa.Column('carbon_stock', sa.Float(), nullable=True),
    sa.Column('carbon_sequestered', sa.Float(), nullable=True),
    sa.Column('biodiversity_score', sa.Float(), nullable=True),
    sa.Column('tree_cover', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_measurements_site_id'), 'site_measurements', ['site_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_measurements_site_id'), table_name='site_measurements')
    op.drop_table('site_measurements')
    # ### end Alembic commands ###
